// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Repositories.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string Title { get; set; }

    public string Isbn13 { get; set; }

    public int AuthorId { get; set; }

    public int? GenreId { get; set; }

    public string Description { get; set; }

    public string CoverImageUrl { get; set; }

    public int? PublicationYear { get; set; }

    public int? PageCount { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Author Author { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<UserBook> UserBooks { get; set; } = new List<UserBook>();
}