// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Repositories.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public string CommentText { get; set; }

    public DateTime DateCommented { get; set; }

    public bool IsEdited { get; set; }

    public DateTime? EditedAt { get; set; }

    public virtual Review Review { get; set; }

    public virtual User User { get; set; }
}