// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Service.Models;

public partial class BookShelf
{
    public int ShelfId { get; set; }

    public int UserId { get; set; }

    public string ShelfName { get; set; }

    public string Description { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? DisplayOrder { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserBook> UserBooks { get; set; } = new List<UserBook>();
}