// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Service.Models;

public partial class ExternalLogin
{
    public int ExternalLoginId { get; set; }

    public int UserId { get; set; }

    public string Provider { get; set; }

    public string ProviderKey { get; set; }

    public virtual User User { get; set; }
}