// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Service.Models;

public partial class ReadingStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public string Description { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<UserBook> UserBooks { get; set; } = new List<UserBook>();
}