// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookNest_Service.Models;

public partial class UserBook
{
    public int UserBookId { get; set; }

    public int UserId { get; set; }

    public int BookId { get; set; }

    public int StatusId { get; set; }

    public int? ShelfId { get; set; }

    public DateTime DateAdded { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? FinishDate { get; set; }

    public int? CurrentPage { get; set; }

    public decimal? ReadingProgress { get; set; }

    public string Notes { get; set; }

    public virtual Book Book { get; set; }

    public virtual BookShelf Shelf { get; set; }

    public virtual ReadingStatus Status { get; set; }

    public virtual User User { get; set; }
}